# Generated by Django 4.1.3 on 2022-12-17 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_service_data',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Mobileno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('service_catg_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prise', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('service_by', models.CharField(max_length=20)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('service_prise', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_app_service_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('slnoo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='store_invoice_data_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('slnoo', models.IntegerField(blank=True, null=True)),
                ('prise', models.IntegerField(blank=True, null=True)),
                ('slno', models.CharField(max_length=30)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('Name', models.CharField(max_length=1000)),
                ('MobileNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1000)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField(default=0, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('vendor_id', models.CharField(max_length=6)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_dev_id', models.TextField()),
                ('dev_limit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('client_service_data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='swalook.client_service_data')),
                ('Discont', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('slno', models.CharField(blank=True, max_length=20, null=True)),
                ('s_gst', models.BigIntegerField(blank=True, null=True)),
                ('c_gst', models.BigIntegerField(blank=True, null=True)),
                ('grand_total', models.BigIntegerField(blank=True, null=True)),
            ],
            bases=('swalook.client_service_data',),
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
